base: --no-source --color --format pretty -p html_report
default: --profile dev

dev: --profile base PROFILE=dev
prod: --profile base PROFILE=prod

html_report: --format progress --format html --out=report/features_report.html
